import localFont from "next/font/local";
import "./globals.css";
import Content from "@/components/content";
import Sidebar from "./@sidebar/page";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, content, sidebar }) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: '20px', backgroundColor: '#f0f0f0' }}>
          <nav>
            <a href="/" style={{ marginRight: '15px' }}>Home</a>
            <a href="/about">About</a>
          </nav>
        </header>
        <main style={{ padding: '20px' }}>
          {content}
          {sidebar}
          {children}
        </main>
        <footer style={{ padding: '10px', textAlign: 'center', backgroundColor: '#f0f0f0' }}>
          Simple Footer Text
        </footer>
      </body>
    </html>
  );
}